# -*- coding: utf-8 -*-
"""Actividad 9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKr74td7zwJTqydLxYQINTqvgFcBx5i6
"""

#1. Importar
from tensorflow.keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

#2. Limpiar datos
x_train = x_train / 255.0
x_test = x_test / 255.0
#Agregar dimensión
x_train = x_train.reshape(-1,28,28,1)
x_test = x_test.reshape(-1,28,28,1)

#3. Data augmentation
from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagen = ImageDataGenerator(
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

#4. Imágenes transformadas
import matplotlib.pyplot as plt

plt.imshow(x_train[0].reshape(28,28), cmap='gray')
plt.show()

#5. Modelo base
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(28,28,1)),
    layers.MaxPooling2D(),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

#6. Entranamiento
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)

#7.Modelo con Data augmentation
model.fit(datagen.flow(x_train, y_train), epochs=5)

#8. Modelo inteligente (Transfer Learning)
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras import layers, models

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(96,96,3))
base_model.trainable = False

#9. Adaptar tamaño de imagenes
import tensorflow as tf

x_train_resized = tf.image.resize(x_train, (96,96))
x_test_resized = tf.image.resize(x_test, (96,96))

#10.Creo modelo
model_tl = models.Sequential([
    base_model,
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

#11. Entreno
import tensorflow as tf

x_train_resized_rgb = tf.image.grayscale_to_rgb(x_train_resized)
x_test_resized_rgb = tf.image.grayscale_to_rgb(x_test_resized)

model_tl.compile(optimizer='adam',
                 loss='sparse_categorical_crossentropy',
                 metrics=['accuracy'])

model_tl.fit(x_train_resized_rgb, y_train, epochs=5)

#12. Evaluo
model.evaluate(x_test, y_test)
model_tl.evaluate(x_test_resized_rgb, y_test)