# -*- coding: utf-8 -*-
"""semana5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mk00ULJ4BnhecxY9GK4oOaHNvVCEMre3
"""

#Importar librerías
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt

#Cargar datos
#Dataset de ropa (camisetas, zapatos, etc)
fashion_mnist=keras.datasets.fashion_mnist

(x_train, y_train), (x_test, y_test)=fashion_mnist.load_data()

#Normalizar datos (0 a 1)
x_train=x_train/255.0
x_test=x_test/255.0

#Crear modelo
def create_model():
      model=keras.Sequential([
            keras.layers.Flatten(input_shape=(28,28)),
            keras.layers.Dense(128, activation='relu'),
            keras.layers.Dense(10, activation='softmax')
      ])
      return model

#Experimento A (Learning rate ALTO)
modelo_A = create_model()
modelo_A.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

historia_A=modelo_A.fit(
    x_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test, y_test)
)

#Experimento B (Learning rate BAJO)
modelo_B=create_model()

modelo_B.compile(
    optimizer=keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

historia_B=modelo_B.fit(
    x_train, y_train,
    epochs=10,
    batch_size=32,
    validation_data=(x_test, y_test)
)

#Graficar resultados
#LOSS
plt.figure()
plt.plot(historia_A.history['loss'], label='Loss A (lr=0.01)')
plt.plot(historia_B.history['loss'], label='Loss B (lr=0.001)')
plt.title('Comparación de Loss')
plt.xlabel('Épocas')
plt.ylabel('Loss')
plt.legend()
plt.show

#ACURRACY
plt.figure()
plt.plot(historia_A.history['accuracy'], label='Acc A (lr=0.01)')
plt.plot(historia_B.history['accuracy'], label='Acc B (lr=0.001)')
plt.title('Comparación de Accurracy')
plt.xlabel('Épocas')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

#EVALUACIÓN FINAL
print("Evaluación modelo A:")
modelo_A.evaluate(x_test, y_test)

print("Evaluación modelo B:")
modelo_B.evaluate(x_test, y_test)